message_thread.template.*:
  type: config_entity
  label: 'Message thread template'
  mapping:
    template:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    text:
      type: sequence
      label: 'Message Text'
      sequence:
        type: text_format
        label: 'Text'
    message_template:
      type: string
      label: 'Message Template'
    view_id:
      type: string
      label: 'Messages View'
    view_display_id:
      type: string
      label: 'Messages View Display'
    view_display:
      type: string
      label: 'View Display'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        message_template:
          type: string
          label: 'Message Template'
        thread_view_id:
          type: string
          label: 'Thread View'
        thread_view_display_id:
          type: string
          label: 'Thread View Display'
        view_id:
          type: string
          label: 'Messages View'
        view_display_id:
          type: string
          label: 'Messages View Display'
        'token options':
          type: mapping
          label: 'Token options'
          mapping:
            clear:
              type: boolean
              label: 'Clear empty tokens'
            token replace:
              type: boolean
              label: 'Replace tokens'
